name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]    

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.0.x
          7.0.x
        include-prerelease: true

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      run: dotnet test --no-restore --logger "console;verbosity=normal"

    - name: Pack and push to nuget.org
      if: github.event_name == 'release'
      run: |
        echo G=${GITHUB_REF}
        vertag=(${GITHUB_REF//\// })
        VERSION="${vertag[2]}"
        [[ "${VERSION:0:1}" == "v" ]] && VERSION="${VERSION:1}" # Remove leading v
        dotnet pack -c Release --include-symbols --include-source -p:PackageVersion="$VERSION" -o nupkg
        dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}}